# -*- coding: utf-8 -*-
"""spam_email_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/155NBv9bTC2s9gNWm2vZW9Juo1jB40rzy
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import streamlit as st

data = pd.read_csv('spam.csv')
print(data.shape)

data.drop_duplicates(inplace=True)
print(data.shape)
print(data.isnull().sum())
print(data.head())

data['Category'] = data['Category'].replace(['ham','spam'],['Not Spam','Spam'])
#print(data.head())
msg = data['Message']
cat = data['Category']
msg_train,msg_test,cat_train,cat_test = train_test_split(msg,cat,test_size=0.2,random_state=1)
cv = CountVectorizer(stop_words='english')
features = cv.fit_transform(msg_train)

#creating model
model = MultinomialNB()
model.fit( features ,cat_train)

#test moodel
features_test = cv.transform(msg_test)
print(model.score(features_test,cat_test))

#predict the data
def predict(message):
  message = cv.transform([message])
  result = model.predict(message)[0]
  return result

st.header('Spam Detection')

output = predict('Congratulation , you have won a lottery')
input_msg = st.text_input('Enter your message')
print(output)

if st.button('Predict'):
  output = predict(input_msg)
  st.text = output
  st.markdown(output)

# message = cv.transform['Congratulation , you have won a lottery'].toarray()
# result = model.predict(message)
# print(result)